### ISSUE TITLE
Error while building on MACOS

### ISSUE THREAD

**Issue by chorfa007** [badaix/jsonrpcpp#14]
Hello,

I cant build the library on 
Darwin MacBook-Pro.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112 arm64
below steps to replicate the issue 👍 
Make a git clone
go to project folder
cmake .
make

You will end with error 

make
[ 25%] Building CXX object example/CMakeFiles/jsonrpcpp_example.dir/jsonrpcpp_example.cpp.o
[ 50%] Linking CXX executable jsonrpcpp_example
[ 50%] Built target jsonrpcpp_example
[ 75%] Building CXX object test/CMakeFiles/jsonrpcpp_test.dir/test_main.cpp.o
In file included from /Users/issamchorfa/jsonrpcpp/jsonrpcpp/test/test_main.cpp:10:
/Users/issamchorfa/jsonrpcpp/jsonrpcpp/test/catch.hpp:8122:13: error: unrecognized instruction mnemonic, did you mean: bit, cnt, hint, ins, not?
            CATCH_BREAK_INTO_DEBUGGER();
            ^
/Users/issamchorfa/jsonrpcpp/jsonrpcpp/test/catch.hpp:7834:79: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() []{ if( Catch::isDebuggerActive() ) { CATCH_TRAP(); } }()
                                                                              ^
/Users/issamchorfa/jsonrpcpp/jsonrpcpp/test/catch.hpp:7813:34: note: expanded from macro 'CATCH_TRAP'
    #define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
                                 ^
<inline asm>:1:2: note: instantiated into assembly here
        int $3
        ^
1 error generated.
make[2]: *** [test/CMakeFiles/jsonrpcpp_test.dir/test_main.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/jsonrpcpp_test.dir/all] Error 2
make: *** [all] Error 2

**Comment by chorfa007** [comment]
including @badaix

**Comment by chorfa007** [comment]
Apply below patch to test/catch.hpp can solve the build error, still need to verify in linux and windows ...

diff --git a/src/external/catch/catch.hpp b/src/external/catch/catch.hpp
index 099119d4..7eece27d 100644
--- a/src/external/catch/catch.hpp
+++ b/src/external/catch/catch.hpp
@@ -5461,7 +5461,11 @@ namespace Catch {

 #ifdef CATCH_PLATFORM_MAC

-    #define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
+    #if defined(__i386__) || defined(__x86_64__)
+        #define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
+    #elif defined(__aarch64__)
+        #define CATCH_TRAP()  __asm__(".inst 0xd4200000")
+    #endif

**Comment by chorfa007** [comment]
Below is the link where you can find the solution. It still needs to be verified on Windows and Linux builds
https://github.com/CoatiSoftware/Sourcetrail/issues/1185

**Comment by badaix** [comment]
I've updated Catch2 to v3.6 in [jsonrpc++ 1.4.0](https://github.com/badaix/jsonrpcpp/releases/tag/v1.4.0) and added tests for 29 more compilers to the CI, including Linux, Mac and Windows, see the [action run](https://github.com/badaix/jsonrpcpp/actions/runs/9453836931)
